In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('../Dataset/INDIA_AQI_COMPLETE_20251126.csv')

In [3]:
df.head()

,City,State,Latitude,Longitude,Datetime,Year,Month,Day,Hour,Day_of_Week,...,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,AQI_Category,PM25_Category_India,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
0,Agartala,Tripura,23.8315,91.2868,2022-08-05 00:00:00,2022,8,5,0,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
1,Agartala,Tripura,23.8315,91.2868,2022-08-05 01:00:00,2022,8,5,1,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
2,Agartala,Tripura,23.8315,91.2868,2022-08-05 02:00:00,2022,8,5,2,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
3,Agartala,Tripura,23.8315,91.2868,2022-08-05 03:00:00,2022,8,5,3,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
4,Agartala,Tripura,23.8315,91.2868,2022-08-05 04:00:00,2022,8,5,4,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0

In [4]:
df.columns

Index(['City', 'State', 'Latitude', 'Longitude', 'Datetime', 'Year', 'Month',
       'Day', 'Hour', 'Day_of_Week', 'Day_Name', 'Week_of_Year', 'Is_Weekend',
       'Quarter', 'Season', 'Time_of_Day', 'Temp_2m_C', 'Temp_80m_C',
       'Temp_120m_C', 'Temp_180m_C', 'Humidity_Percent', 'Dew_Point_C',
       'Humidity_Category', 'Wind_Speed_10m_kmh', 'Wind_Speed_80m_kmh',
       'Wind_Speed_120m_kmh', 'Wind_Dir_10m', 'Wind_Gusts_kmh',
       'Wind_Category', 'Wind_Stagnation', 'Precipitation_mm', 'Rain_mm',
       'Is_Raining', 'Heavy_Rain', 'Pressure_MSL_hPa', 'Surface_Pressure_hPa',
       'Solar_Radiation_Wm2', 'Direct_Radiation_Wm2', 'Diffuse_Radiation_Wm2',
       'UV_Index', 'Cloud_Cover_Percent', 'Cloud_Low_Percent',
       'Cloud_Mid_Percent', 'Cloud_High_Percent', 'Is_Daytime',
       'Sunshine_Seconds', 'PM2_5_ugm3', 'PM10_ugm3', 'PM_Ratio', 'CO_ugm3',
       'NO2_ugm3', 'SO2_ugm3', 'O3_ugm3', 'Dust_ugm3', 'NH3_ugm3', 'AOD',
       'US_AQI', 'US_AQI_PM25', 'US_AQI_PM10', 'US_AQI_NO2', 'US_AQI_O3',
       'US_AQI_CO', 'EU_AQI', 'EU_AQI_PM25', 'EU_AQI_PM10', 'AQI_Category',
       'PM25_Category_India', 'Temp_Inversion', 'Inversion_Strength_C',
       'Festival_Period', 'Crop_Burning_Season'],
      dtype='str')

In [5]:
len(df.columns)

71

In [6]:
#dropping redundant date time columns
df.drop(columns=['Time_of_Day','Datetime','Day','Year','Quarter','Day_of_Week','Day_Name','Season'],inplace=True)

In [7]:
pd.set_option('display.max_columns',None)

In [8]:
df.head()

,City,State,Latitude,Longitude,Month,Hour,Week_of_Year,Is_Weekend,Temp_2m_C,Temp_80m_C,Temp_120m_C,Temp_180m_C,Humidity_Percent,Dew_Point_C,Humidity_Category,Wind_Speed_10m_kmh,Wind_Speed_80m_kmh,Wind_Speed_120m_kmh,Wind_Dir_10m,Wind_Gusts_kmh,Wind_Category,Wind_Stagnation,Precipitation_mm,Rain_mm,Is_Raining,Heavy_Rain,Pressure_MSL_hPa,Surface_Pressure_hPa,Solar_Radiation_Wm2,Direct_Radiation_Wm2,Diffuse_Radiation_Wm2,UV_Index,Cloud_Cover_Percent,Cloud_Low_Percent,Cloud_Mid_Percent,Cloud_High_Percent,Is_Daytime,Sunshine_Seconds,PM2_5_ugm3,PM10_ugm3,PM_Ratio,CO_ugm3,NO2_ugm3,SO2_ugm3,O3_ugm3,Dust_ugm3,NH3_ugm3,AOD,US_AQI,US_AQI_PM25,US_AQI_PM10,US_AQI_NO2,US_AQI_O3,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,AQI_Category,PM25_Category_India,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
0,Agartala,Tripura,23.8315,91.2868,8,0,31,0,26.7,NaN,NaN,NaN,91,25.1,Very_Humid,5.4,NaN,NaN,172,11.2,Moderate,0,0.0,0.0,0,0,1004.4,1003.0,0.0,0.0,0.0,NaN,100,0,7,100,0,0.0,14.8,21.5,0.688372,197.0,21.8,2.7,32.0,0.0,NaN,0.14,NaN,NaN,NaN,11.0,16.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
1,Agartala,Tripura,23.8315,91.2868,8,1,31,0,26.4,NaN,NaN,NaN,93,25.2,Very_Humid,4.5,NaN,NaN,166,9.0,Light,0,0.0,0.0,0,0,1003.9,1002.5,0.0,0.0,0.0,NaN,100,3,4,100,0,0.0,15.7,22.8,0.688596,196.0,18.5,3.0,33.0,0.0,NaN,0.14,NaN,NaN,NaN,9.0,14.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
2,Agartala,Tripura,23.8315,91.2868,8,2,31,0,26.1,NaN,NaN,NaN,95,25.2,Very_Humid,3.8,NaN,NaN,163,7.6,Light,0,0.0,0.0,0,0,1003.5,1002.1,0.0,0.0,0.0,NaN,100,2,2,100,0,0.0,16.3,23.5,0.693617,196.0,15.1,3.3,34.0,0.0,NaN,0.15,NaN,NaN,NaN,7.0,14.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
3,Agartala,Tripura,23.8315,91.2868,8,3,31,0,26.0,NaN,NaN,NaN,96,25.2,Very_Humid,3.7,NaN,NaN,151,6.8,Light,0,0.0,0.0,0,0,1003.0,1001.6,0.0,0.0,0.0,NaN,100,0,1,100,0,0.0,17.6,25.4,0.692913,197.0,14.1,3.3,32.0,0.0,NaN,0.15,NaN,NaN,NaN,7.0,14.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
4,Agartala,Tripura,23.8315,91.2868,8,4,31,0,25.8,NaN,NaN,NaN,97,25.2,Very_Humid,4.1,NaN,NaN,128,6.8,Light,0,0.0,0.0,0,0,1002.9,1001.5,0.0,0.0,0.0,NaN,100,0,1,100,0,0.0,18.2,26.2,0.694656,199.0,13.9,3.2,30.0,0.0,NaN,0.14,NaN,NaN,NaN,7.0,14.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0

In [9]:
df.columns

Index(['City', 'State', 'Latitude', 'Longitude', 'Month', 'Hour',
       'Week_of_Year', 'Is_Weekend', 'Temp_2m_C', 'Temp_80m_C', 'Temp_120m_C',
       'Temp_180m_C', 'Humidity_Percent', 'Dew_Point_C', 'Humidity_Category',
       'Wind_Speed_10m_kmh', 'Wind_Speed_80m_kmh', 'Wind_Speed_120m_kmh',
       'Wind_Dir_10m', 'Wind_Gusts_kmh', 'Wind_Category', 'Wind_Stagnation',
       'Precipitation_mm', 'Rain_mm', 'Is_Raining', 'Heavy_Rain',
       'Pressure_MSL_hPa', 'Surface_Pressure_hPa', 'Solar_Radiation_Wm2',
       'Direct_Radiation_Wm2', 'Diffuse_Radiation_Wm2', 'UV_Index',
       'Cloud_Cover_Percent', 'Cloud_Low_Percent', 'Cloud_Mid_Percent',
       'Cloud_High_Percent', 'Is_Daytime', 'Sunshine_Seconds', 'PM2_5_ugm3',
       'PM10_ugm3', 'PM_Ratio', 'CO_ugm3', 'NO2_ugm3', 'SO2_ugm3', 'O3_ugm3',
       'Dust_ugm3', 'NH3_ugm3', 'AOD', 'US_AQI', 'US_AQI_PM25', 'US_AQI_PM10',
       'US_AQI_NO2', 'US_AQI_O3', 'US_AQI_CO', 'EU_AQI', 'EU_AQI_PM25',
       'EU_AQI_PM10', 'AQI_Category', 'PM25_Category_India', 'Temp_Inversion',
       'Inversion_Strength_C', 'Festival_Period', 'Crop_Burning_Season'],
      dtype='str')

In [10]:
# dropping redundant geographical columns
df.drop(columns=['Longitude','Latitude','Temp_180m_C','Temp_120m_C','Temp_2m_C','Temp_80m_C',],inplace=True)

In [11]:
# drop redundant temperature columns
df.drop(columns=[],inplace=True)

In [12]:
# dropping redundant Wind-related columns
df.drop(columns=['Wind_Stagnation','Wind_Gusts_kmh','Wind_Dir_10m','Wind_Speed_80m_kmh','Wind_Speed_120m_kmh','Wind_Category'],inplace=True)

In [13]:
len(df.columns)

51

In [14]:

df['City'].value_counts()

City
Agartala              29040
Ahmedabad             29040
Aizawl                29040
Bengaluru             29040
Bhopal                29040
Bhubaneswar           29040
Chandigarh            29040
Chennai               29040
Dehradun              29040
Delhi                 29040
Gangtok               29040
Gurugram              29040
Guwahati              29040
Hyderabad             29040
Imphal                29040
Itanagar              29040
Jaipur                29040
Kohima                29040
Kolkata               29040
Lucknow               29040
Mumbai                29040
Panaji                29040
Patna                 29040
Raipur                29040
Ranchi                29040
Shillong              29040
Shimla                29040
Thiruvananthapuram    29040
Visakhapatnam         29040
Name: count, dtype: int64

In [15]:
df.columns

Index(['City', 'State', 'Month', 'Hour', 'Week_of_Year', 'Is_Weekend',
       'Humidity_Percent', 'Dew_Point_C', 'Humidity_Category',
       'Wind_Speed_10m_kmh', 'Precipitation_mm', 'Rain_mm', 'Is_Raining',
       'Heavy_Rain', 'Pressure_MSL_hPa', 'Surface_Pressure_hPa',
       'Solar_Radiation_Wm2', 'Direct_Radiation_Wm2', 'Diffuse_Radiation_Wm2',
       'UV_Index', 'Cloud_Cover_Percent', 'Cloud_Low_Percent',
       'Cloud_Mid_Percent', 'Cloud_High_Percent', 'Is_Daytime',
       'Sunshine_Seconds', 'PM2_5_ugm3', 'PM10_ugm3', 'PM_Ratio', 'CO_ugm3',
       'NO2_ugm3', 'SO2_ugm3', 'O3_ugm3', 'Dust_ugm3', 'NH3_ugm3', 'AOD',
       'US_AQI', 'US_AQI_PM25', 'US_AQI_PM10', 'US_AQI_NO2', 'US_AQI_O3',
       'US_AQI_CO', 'EU_AQI', 'EU_AQI_PM25', 'EU_AQI_PM10', 'AQI_Category',
       'PM25_Category_India', 'Temp_Inversion', 'Inversion_Strength_C',
       'Festival_Period', 'Crop_Burning_Season'],
      dtype='str')