In [112]:
import pandas as pd

In [113]:
df=pd.read_csv('../Dataset/INDIA_AQI_COMPLETE_20251126.csv')

In [114]:
df.head()

,City,State,Latitude,Longitude,Datetime,Year,Month,Day,Hour,Day_of_Week,Day_Name,Week_of_Year,Is_Weekend,Quarter,Season,Time_of_Day,Temp_2m_C,Temp_80m_C,Temp_120m_C,Temp_180m_C,Humidity_Percent,Dew_Point_C,Humidity_Category,Wind_Speed_10m_kmh,Wind_Speed_80m_kmh,Wind_Speed_120m_kmh,Wind_Dir_10m,Wind_Gusts_kmh,Wind_Category,Wind_Stagnation,Precipitation_mm,Rain_mm,Is_Raining,Heavy_Rain,Pressure_MSL_hPa,Surface_Pressure_hPa,Solar_Radiation_Wm2,Direct_Radiation_Wm2,Diffuse_Radiation_Wm2,UV_Index,Cloud_Cover_Percent,Cloud_Low_Percent,Cloud_Mid_Percent,Cloud_High_Percent,Is_Daytime,Sunshine_Seconds,PM2_5_ugm3,PM10_ugm3,PM_Ratio,CO_ugm3,NO2_ugm3,SO2_ugm3,O3_ugm3,Dust_ugm3,NH3_ugm3,AOD,US_AQI,US_AQI_PM25,US_AQI_PM10,US_AQI_NO2,US_AQI_O3,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,AQI_Category,PM25_Category_India,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
0,Agartala,Tripura,23.8315,91.2868,2022-08-05 00:00:00,2022,8,5,0,4,Friday,31,0,3,Monsoon,Night,26.7,NaN,NaN,NaN,91,25.1,Very_Humid,5.4,NaN,NaN,172,11.2,Moderate,0,0.0,0.0,0,0,1004.4,1003.0,0.0,0.0,0.0,NaN,100,0,7,100,0,0.0,14.8,21.5,0.688372,197.0,21.8,2.7,32.0,0.0,NaN,0.14,NaN,NaN,NaN,11.0,16.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
1,Agartala,Tripura,23.8315,91.2868,2022-08-05 01:00:00,2022,8,5,1,4,Friday,31,0,3,Monsoon,Night,26.4,NaN,NaN,NaN,93,25.2,Very_Humid,4.5,NaN,NaN,166,9.0,Light,0,0.0,0.0,0,0,1003.9,1002.5,0.0,0.0,0.0,NaN,100,3,4,100,0,0.0,15.7,22.8,0.688596,196.0,18.5,3.0,33.0,0.0,NaN,0.14,NaN,NaN,NaN,9.0,14.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
2,Agartala,Tripura,23.8315,91.2868,2022-08-05 02:00:00,2022,8,5,2,4,Friday,31,0,3,Monsoon,Night,26.1,NaN,NaN,NaN,95,25.2,Very_Humid,3.8,NaN,NaN,163,7.6,Light,0,0.0,0.0,0,0,1003.5,1002.1,0.0,0.0,0.0,NaN,100,2,2,100,0,0.0,16.3,23.5,0.693617,196.0,15.1,3.3,34.0,0.0,NaN,0.15,NaN,NaN,NaN,7.0,14.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
3,Agartala,Tripura,23.8315,91.2868,2022-08-05 03:00:00,2022,8,5,3,4,Friday,31,0,3,Monsoon,Night,26.0,NaN,NaN,NaN,96,25.2,Very_Humid,3.7,NaN,NaN,151,6.8,Light,0,0.0,0.0,0,0,1003.0,1001.6,0.0,0.0,0.0,NaN,100,0,1,100,0,0.0,17.6,25.4,0.692913,197.0,14.1,3.3,32.0,0.0,NaN,0.15,NaN,NaN,NaN,7.0,14.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
4,Agartala,Tripura,23.8315,91.2868,2022-08-05 04:00:00,2022,8,5,4,4,Friday,31,0,3,Monsoon,Night,25.8,NaN,NaN,NaN,97,25.2,Very_Humid,4.1,NaN,NaN,128,6.8,Light,0,0.0,0.0,0,0,1002.9,1001.5,0.0,0.0,0.0,NaN,100,0,1,100,0,0.0,18.2,26.2,0.694656,199.0,13.9,3.2,30.0,0.0,NaN,0.14,NaN,NaN,NaN,7.0,14.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0

In [115]:
df.columns

Index(['City', 'State', 'Latitude', 'Longitude', 'Datetime', 'Year', 'Month',
       'Day', 'Hour', 'Day_of_Week', 'Day_Name', 'Week_of_Year', 'Is_Weekend',
       'Quarter', 'Season', 'Time_of_Day', 'Temp_2m_C', 'Temp_80m_C',
       'Temp_120m_C', 'Temp_180m_C', 'Humidity_Percent', 'Dew_Point_C',
       'Humidity_Category', 'Wind_Speed_10m_kmh', 'Wind_Speed_80m_kmh',
       'Wind_Speed_120m_kmh', 'Wind_Dir_10m', 'Wind_Gusts_kmh',
       'Wind_Category', 'Wind_Stagnation', 'Precipitation_mm', 'Rain_mm',
       'Is_Raining', 'Heavy_Rain', 'Pressure_MSL_hPa', 'Surface_Pressure_hPa',
       'Solar_Radiation_Wm2', 'Direct_Radiation_Wm2', 'Diffuse_Radiation_Wm2',
       'UV_Index', 'Cloud_Cover_Percent', 'Cloud_Low_Percent',
       'Cloud_Mid_Percent', 'Cloud_High_Percent', 'Is_Daytime',
       'Sunshine_Seconds', 'PM2_5_ugm3', 'PM10_ugm3', 'PM_Ratio', 'CO_ugm3',
       'NO2_ugm3', 'SO2_ugm3', 'O3_ugm3', 'Dust_ugm3', 'NH3_ugm3', 'AOD',
       'US_AQI', 'US_AQI_PM25', 'US_AQI_PM10', 'US_AQI_NO2', 'US_AQI_O3',
       'US_AQI_CO', 'EU_AQI', 'EU_AQI_PM25', 'EU_AQI_PM10', 'AQI_Category',
       'PM25_Category_India', 'Temp_Inversion', 'Inversion_Strength_C',
       'Festival_Period', 'Crop_Burning_Season'],
      dtype='str')

In [116]:
len(df.columns)

71

In [117]:
#dropping redundant date time columns
df.drop(columns=['Hour','Is_Daytime','Week_of_Year','Time_of_Day','Datetime','Day','Year','Quarter','Day_of_Week','Day_Name','Season'],inplace=True)

In [118]:
pd.set_option('display.max_columns',None)

In [119]:
df.head()

,City,State,Latitude,Longitude,Month,Is_Weekend,Temp_2m_C,Temp_80m_C,Temp_120m_C,Temp_180m_C,Humidity_Percent,Dew_Point_C,Humidity_Category,Wind_Speed_10m_kmh,Wind_Speed_80m_kmh,Wind_Speed_120m_kmh,Wind_Dir_10m,Wind_Gusts_kmh,Wind_Category,Wind_Stagnation,Precipitation_mm,Rain_mm,Is_Raining,Heavy_Rain,Pressure_MSL_hPa,Surface_Pressure_hPa,Solar_Radiation_Wm2,Direct_Radiation_Wm2,Diffuse_Radiation_Wm2,UV_Index,Cloud_Cover_Percent,Cloud_Low_Percent,Cloud_Mid_Percent,Cloud_High_Percent,Sunshine_Seconds,PM2_5_ugm3,PM10_ugm3,PM_Ratio,CO_ugm3,NO2_ugm3,SO2_ugm3,O3_ugm3,Dust_ugm3,NH3_ugm3,AOD,US_AQI,US_AQI_PM25,US_AQI_PM10,US_AQI_NO2,US_AQI_O3,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,AQI_Category,PM25_Category_India,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
0,Agartala,Tripura,23.8315,91.2868,8,0,26.7,NaN,NaN,NaN,91,25.1,Very_Humid,5.4,NaN,NaN,172,11.2,Moderate,0,0.0,0.0,0,0,1004.4,1003.0,0.0,0.0,0.0,NaN,100,0,7,100,0.0,14.8,21.5,0.688372,197.0,21.8,2.7,32.0,0.0,NaN,0.14,NaN,NaN,NaN,11.0,16.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
1,Agartala,Tripura,23.8315,91.2868,8,0,26.4,NaN,NaN,NaN,93,25.2,Very_Humid,4.5,NaN,NaN,166,9.0,Light,0,0.0,0.0,0,0,1003.9,1002.5,0.0,0.0,0.0,NaN,100,3,4,100,0.0,15.7,22.8,0.688596,196.0,18.5,3.0,33.0,0.0,NaN,0.14,NaN,NaN,NaN,9.0,14.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
2,Agartala,Tripura,23.8315,91.2868,8,0,26.1,NaN,NaN,NaN,95,25.2,Very_Humid,3.8,NaN,NaN,163,7.6,Light,0,0.0,0.0,0,0,1003.5,1002.1,0.0,0.0,0.0,NaN,100,2,2,100,0.0,16.3,23.5,0.693617,196.0,15.1,3.3,34.0,0.0,NaN,0.15,NaN,NaN,NaN,7.0,14.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
3,Agartala,Tripura,23.8315,91.2868,8,0,26.0,NaN,NaN,NaN,96,25.2,Very_Humid,3.7,NaN,NaN,151,6.8,Light,0,0.0,0.0,0,0,1003.0,1001.6,0.0,0.0,0.0,NaN,100,0,1,100,0.0,17.6,25.4,0.692913,197.0,14.1,3.3,32.0,0.0,NaN,0.15,NaN,NaN,NaN,7.0,14.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
4,Agartala,Tripura,23.8315,91.2868,8,0,25.8,NaN,NaN,NaN,97,25.2,Very_Humid,4.1,NaN,NaN,128,6.8,Light,0,0.0,0.0,0,0,1002.9,1001.5,0.0,0.0,0.0,NaN,100,0,1,100,0.0,18.2,26.2,0.694656,199.0,13.9,3.2,30.0,0.0,NaN,0.14,NaN,NaN,NaN,7.0,14.0,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0

In [120]:
df.columns

Index(['City', 'State', 'Latitude', 'Longitude', 'Month', 'Is_Weekend',
       'Temp_2m_C', 'Temp_80m_C', 'Temp_120m_C', 'Temp_180m_C',
       'Humidity_Percent', 'Dew_Point_C', 'Humidity_Category',
       'Wind_Speed_10m_kmh', 'Wind_Speed_80m_kmh', 'Wind_Speed_120m_kmh',
       'Wind_Dir_10m', 'Wind_Gusts_kmh', 'Wind_Category', 'Wind_Stagnation',
       'Precipitation_mm', 'Rain_mm', 'Is_Raining', 'Heavy_Rain',
       'Pressure_MSL_hPa', 'Surface_Pressure_hPa', 'Solar_Radiation_Wm2',
       'Direct_Radiation_Wm2', 'Diffuse_Radiation_Wm2', 'UV_Index',
       'Cloud_Cover_Percent', 'Cloud_Low_Percent', 'Cloud_Mid_Percent',
       'Cloud_High_Percent', 'Sunshine_Seconds', 'PM2_5_ugm3', 'PM10_ugm3',
       'PM_Ratio', 'CO_ugm3', 'NO2_ugm3', 'SO2_ugm3', 'O3_ugm3', 'Dust_ugm3',
       'NH3_ugm3', 'AOD', 'US_AQI', 'US_AQI_PM25', 'US_AQI_PM10', 'US_AQI_NO2',
       'US_AQI_O3', 'US_AQI_CO', 'EU_AQI', 'EU_AQI_PM25', 'EU_AQI_PM10',
       'AQI_Category', 'PM25_Category_India', 'Temp_Inversion',
       'Inversion_Strength_C', 'Festival_Period', 'Crop_Burning_Season'],
      dtype='str')

In [121]:
# dropping redundant geographical columns
df.drop(columns=['Longitude','Latitude','Temp_180m_C','Temp_120m_C','Temp_2m_C','Temp_80m_C',],inplace=True)

In [122]:
# drop redundant temperature columns
df.drop(columns=[],inplace=True)

In [123]:
# dropping redundant Wind-related columns
df.drop(columns=['Wind_Stagnation','Wind_Gusts_kmh','Wind_Dir_10m','Wind_Speed_80m_kmh','Wind_Speed_120m_kmh','Wind_Category'],inplace=True)

In [124]:
len(df.columns)

48

In [125]:

df['City'].value_counts()

City
Agartala              29040
Ahmedabad             29040
Aizawl                29040
Bengaluru             29040
Bhopal                29040
Bhubaneswar           29040
Chandigarh            29040
Chennai               29040
Dehradun              29040
Delhi                 29040
Gangtok               29040
Gurugram              29040
Guwahati              29040
Hyderabad             29040
Imphal                29040
Itanagar              29040
Jaipur                29040
Kohima                29040
Kolkata               29040
Lucknow               29040
Mumbai                29040
Panaji                29040
Patna                 29040
Raipur                29040
Ranchi                29040
Shillong              29040
Shimla                29040
Thiruvananthapuram    29040
Visakhapatnam         29040
Name: count, dtype: int64

In [126]:
df.columns

Index(['City', 'State', 'Month', 'Is_Weekend', 'Humidity_Percent',
       'Dew_Point_C', 'Humidity_Category', 'Wind_Speed_10m_kmh',
       'Precipitation_mm', 'Rain_mm', 'Is_Raining', 'Heavy_Rain',
       'Pressure_MSL_hPa', 'Surface_Pressure_hPa', 'Solar_Radiation_Wm2',
       'Direct_Radiation_Wm2', 'Diffuse_Radiation_Wm2', 'UV_Index',
       'Cloud_Cover_Percent', 'Cloud_Low_Percent', 'Cloud_Mid_Percent',
       'Cloud_High_Percent', 'Sunshine_Seconds', 'PM2_5_ugm3', 'PM10_ugm3',
       'PM_Ratio', 'CO_ugm3', 'NO2_ugm3', 'SO2_ugm3', 'O3_ugm3', 'Dust_ugm3',
       'NH3_ugm3', 'AOD', 'US_AQI', 'US_AQI_PM25', 'US_AQI_PM10', 'US_AQI_NO2',
       'US_AQI_O3', 'US_AQI_CO', 'EU_AQI', 'EU_AQI_PM25', 'EU_AQI_PM10',
       'AQI_Category', 'PM25_Category_India', 'Temp_Inversion',
       'Inversion_Strength_C', 'Festival_Period', 'Crop_Burning_Season'],
      dtype='str')

In [127]:
df.drop(columns=[
'US_AQI_PM25',
'US_AQI_PM10',
'US_AQI_NO2',
'US_AQI_O3',
'US_AQI_CO',
'EU_AQI',
'EU_AQI_PM25',
'EU_AQI_PM10',
'AQI_Category',
'PM25_Category_India'
],inplace=True)

In [128]:
df.columns

Index(['City', 'State', 'Month', 'Is_Weekend', 'Humidity_Percent',
       'Dew_Point_C', 'Humidity_Category', 'Wind_Speed_10m_kmh',
       'Precipitation_mm', 'Rain_mm', 'Is_Raining', 'Heavy_Rain',
       'Pressure_MSL_hPa', 'Surface_Pressure_hPa', 'Solar_Radiation_Wm2',
       'Direct_Radiation_Wm2', 'Diffuse_Radiation_Wm2', 'UV_Index',
       'Cloud_Cover_Percent', 'Cloud_Low_Percent', 'Cloud_Mid_Percent',
       'Cloud_High_Percent', 'Sunshine_Seconds', 'PM2_5_ugm3', 'PM10_ugm3',
       'PM_Ratio', 'CO_ugm3', 'NO2_ugm3', 'SO2_ugm3', 'O3_ugm3', 'Dust_ugm3',
       'NH3_ugm3', 'AOD', 'US_AQI', 'Temp_Inversion', 'Inversion_Strength_C',
       'Festival_Period', 'Crop_Burning_Season'],
      dtype='str')

In [129]:
df.drop(columns=['Humidity_Category','Rain_mm','Is_Raining','Heavy_Rain','Cloud_Low_Percent','Cloud_Mid_Percent','Cloud_High_Percent','Direct_Radiation_Wm2','Diffuse_Radiation_Wm2'],inplace=True)

In [130]:
df.columns

Index(['City', 'State', 'Month', 'Is_Weekend', 'Humidity_Percent',
       'Dew_Point_C', 'Wind_Speed_10m_kmh', 'Precipitation_mm',
       'Pressure_MSL_hPa', 'Surface_Pressure_hPa', 'Solar_Radiation_Wm2',
       'UV_Index', 'Cloud_Cover_Percent', 'Sunshine_Seconds', 'PM2_5_ugm3',
       'PM10_ugm3', 'PM_Ratio', 'CO_ugm3', 'NO2_ugm3', 'SO2_ugm3', 'O3_ugm3',
       'Dust_ugm3', 'NH3_ugm3', 'AOD', 'US_AQI', 'Temp_Inversion',
       'Inversion_Strength_C', 'Festival_Period', 'Crop_Burning_Season'],
      dtype='str')

In [131]:
df['Month'].value_counts()

Month
10    86304
8     83520
9     83520
11    80736
12    64728
1     64728
3     64728
5     64728
7     64728
4     62640
6     62640
2     59160
Name: count, dtype: int64

In [132]:
df['Humidity_Percent'].value_counts()

Humidity_Percent
94    22439
93    22407
96    22154
95    22079
91    21116
      ...
7       242
6       125
5        53
4        26
3         6
Name: count, Length: 98, dtype: int64

In [133]:
df['Dew_Point_C'].value_counts()

Dew_Point_C
 23.9    7892
 23.8    7866
 24.0    7840
 23.5    7720
 23.6    7691
         ...
-17.9       1
-18.2       1
-18.3       1
-14.7       1
-16.8       1
Name: count, Length: 505, dtype: int64

In [134]:
df['Wind_Speed_10m_kmh'].value_counts()

Wind_Speed_10m_kmh
5.4     11063
4.7     10709
4.0     10468
3.6     10236
3.1      9939
        ...
40.8        1
42.5        1
40.9        1
36.8        1
38.6        1
Name: count, Length: 433, dtype: int64

In [135]:
df['Precipitation_mm'].value_counts()

Precipitation_mm
0.0     669793
0.1      56223
0.2      24648
0.3      14325
0.4       9890
         ...
23.7         1
22.2         1
28.0         1
33.5         1
24.1         1
Name: count, Length: 255, dtype: int64

In [136]:
df['Pressure_MSL_hPa'].value_counts()

Pressure_MSL_hPa
1011.6    5599
1011.4    5542
1012.9    5538
1011.5    5493
1011.7    5480
          ...
988.6        1
988.1        1
987.6        1
988.3        1
1027.7       1
Name: count, Length: 411, dtype: int64

In [137]:
df['Surface_Pressure_hPa'].value_counts()

Surface_Pressure_hPa
1008.9    2349
1007.7    2346
1007.6    2342
1008.4    2336
1006.9    2324
          ...
770.6        1
770.5        1
794.8        1
794.9        1
794.4        1
Name: count, Length: 1928, dtype: int64

In [138]:
df['Solar_Radiation_Wm2'].value_counts()

Solar_Radiation_Wm2
0.0       395009
1.0         5969
2.0         4101
3.0         3279
4.0         2977
           ...
1031.0         1
1027.0         1
1038.0         1
1037.0         1
1033.0         1
Name: count, Length: 1040, dtype: int64

In [139]:
df['UV_Index'].value_counts()

Series([], Name: count, dtype: int64)

In [140]:
df.drop(columns=['UV_Index'],inplace=True)

In [141]:
df['Cloud_Cover_Percent'].value_counts()

Cloud_Cover_Percent
100    233537
0      190390
99      24235
1       20124
2       13970
        ...
67       2119
68       2114
62       2113
60       2098
61       2043
Name: count, Length: 101, dtype: int64

In [142]:
df['Sunshine_Seconds'].value_counts()

Sunshine_Seconds
0.00       481120
3600.00    292443
888.14          4
3576.96         4
2659.76         4
            ...
3588.84         1
830.31          1
3552.60         1
3515.76         1
722.20          1
Name: count, Length: 62326, dtype: int64

In [143]:
df['PM2_5_ugm3'].value_counts()

PM2_5_ugm3
13.4     2540
11.4     2512
13.6     2502
12.0     2492
10.9     2488
         ...
360.4       1
392.1       1
448.0       1
362.3       1
349.2       1
Name: count, Length: 1213, dtype: int64

In [144]:
df['PM10_ugm3'].value_counts()

PM10_ugm3
19.2      1694
19.3      1682
16.1      1647
19.7      1646
20.8      1634
          ...
2294.8       1
1579.5       1
784.2        1
1683.8       1
1665.2       1
Name: count, Length: 1945, dtype: int64

In [145]:
df['PM10_ugm3'].value_counts()

PM10_ugm3
19.2      1694
19.3      1682
16.1      1647
19.7      1646
20.8      1634
          ...
2294.8       1
1579.5       1
784.2        1
1683.8       1
1665.2       1
Name: count, Length: 1945, dtype: int64

In [146]:
df['PM_Ratio'].value_counts()

PM_Ratio
1.000000    9350
0.700000    4125
0.700000    2598
0.692308    2573
0.666667    2468
            ...
0.952598       1
0.957130       1
0.960501       1
0.959961       1
0.963867       1
Name: count, Length: 126158, dtype: int64

In [147]:
df['CO_ugm3'].value_counts()

CO_ugm3
246.0     2429
237.0     2423
262.0     2416
238.0     2386
241.0     2368
          ...
4326.0       1
2995.0       1
2932.0       1
4074.0       1
3678.0       1
Name: count, Length: 5024, dtype: int64

In [148]:
df['NO2_ugm3'].value_counts()

NO2_ugm3
0.9      7423
1.5      7359
1.1      7275
1.4      7220
1.0      7163
         ...
207.7       1
177.3       1
205.7       1
215.0       1
132.7       1
Name: count, Length: 2120, dtype: int64

In [149]:
df['O3_ugm3'].value_counts()

O3_ugm3
52.0     8388
47.0     8357
54.0     8343
51.0     8329
50.0     8300
         ...
418.0       1
454.0       1
482.0       1
523.0       1
500.0       1
Name: count, Length: 575, dtype: int64

In [150]:
df['NH3_ugm3'].value_counts()

Series([], Name: count, dtype: int64)

In [151]:
df.drop(columns=['NH3_ugm3'],inplace=True)

In [152]:
df['Temp_Inversion'].value_counts()

Temp_Inversion
0    842160
Name: count, dtype: int64

In [153]:
df.drop(
    ['Temp_Inversion', 'Inversion_Strength_C'],
    axis=1,
    inplace=True
)

In [158]:
df.columns

Index(['City', 'State', 'Month', 'Is_Weekend', 'Humidity_Percent',
       'Dew_Point_C', 'Wind_Speed_10m_kmh', 'Precipitation_mm',
       'Pressure_MSL_hPa', 'Surface_Pressure_hPa', 'Solar_Radiation_Wm2',
       'Cloud_Cover_Percent', 'Sunshine_Seconds', 'PM2_5_ugm3', 'PM10_ugm3',
       'PM_Ratio', 'CO_ugm3', 'NO2_ugm3', 'SO2_ugm3', 'O3_ugm3', 'Dust_ugm3',
       'AOD', 'US_AQI', 'Festival_Period', 'Crop_Burning_Season'],
      dtype='str')