In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('../Dataset/clean_data.csv')

In [6]:
df.head()

,Unnamed: 0,City,State,Month,Is_Weekend,Humidity_Percent,Dew_Point_C,Wind_Speed_10m_kmh,Precipitation_mm,Pressure_MSL_hPa,...,PM_Ratio,CO_ugm3,NO2_ugm3,SO2_ugm3,O3_ugm3,Dust_ugm3,AOD,US_AQI,Festival_Period,Crop_Burning_Season
0,5,Agartala,Tripura,8,0,95,25.7,4.3,0.0,1003.5,...,0.692029,210.0,16.4,3.5,26.0,0.0,0.13,54.0,0,0
1,6,Agartala,Tripura,8,0,89,26.0,3.4,0.0,1003.7,...,0.686441,197.0,15.6,3.6,31.0,0.0,0.13,55.0,0,0
2,7,Agartala,Tripura,8,0,82,25.9,4.0,0.0,1004.1,...,0.677966,180.0,14.5,3.7,39.0,0.0,0.12,55.0,0,0
3,8,Agartala,Tripura,8,0,78,26.1,6.1,0.1,1004.4,...,0.677852,160.0,12.8,3.6,50.0,0.0,0.13,55.0,0,0
4,9,Agartala,Tripura,8,0,73,25.8,3.5,0.1,1003.7,...,0.677019,153.0,10.9,3.2,60.0,0.0,0.16,54.0,0,0

In [7]:
df.isna().sum()

Unnamed: 0              0
City                    0
State                   0
Month                   0
Is_Weekend              0
Humidity_Percent        0
Dew_Point_C             0
Wind_Speed_10m_kmh      0
Precipitation_mm        0
Pressure_MSL_hPa        0
Surface_Pressure_hPa    0
Solar_Radiation_Wm2     0
Cloud_Cover_Percent     0
Sunshine_Seconds        0
PM2_5_ugm3              0
PM10_ugm3               0
PM_Ratio                0
CO_ugm3                 0
NO2_ugm3                0
SO2_ugm3                0
O3_ugm3                 0
Dust_ugm3               0
AOD                     0
US_AQI                  0
Festival_Period         0
Crop_Burning_Season     0
dtype: int64

In [8]:
df.dtypes

Unnamed: 0                int64
City                        str
State                       str
Month                     int64
Is_Weekend                int64
Humidity_Percent          int64
Dew_Point_C             float64
Wind_Speed_10m_kmh      float64
Precipitation_mm        float64
Pressure_MSL_hPa        float64
Surface_Pressure_hPa    float64
Solar_Radiation_Wm2     float64
Cloud_Cover_Percent       int64
Sunshine_Seconds        float64
PM2_5_ugm3              float64
PM10_ugm3               float64
PM_Ratio                float64
CO_ugm3                 float64
NO2_ugm3                float64
SO2_ugm3                float64
O3_ugm3                 float64
Dust_ugm3               float64
AOD                     float64
US_AQI                  float64
Festival_Period           int64
Crop_Burning_Season       int64
dtype: object

In [9]:
df["City"].nunique()

29

In [10]:
print(df["City"].unique())

<StringArray>
[          'Agartala',          'Ahmedabad',             'Aizawl',
          'Bengaluru',             'Bhopal',        'Bhubaneswar',
         'Chandigarh',            'Chennai',           'Dehradun',
              'Delhi',            'Gangtok',           'Gurugram',
           'Guwahati',          'Hyderabad',             'Imphal',
           'Itanagar',             'Jaipur',             'Kohima',
            'Kolkata',            'Lucknow',             'Mumbai',
             'Panaji',              'Patna',             'Raipur',
             'Ranchi',           'Shillong',             'Shimla',
 'Thiruvananthapuram',      'Visakhapatnam']
Length: 29, dtype: str

In [11]:
df.drop(columns=["State"], inplace=True)

In [12]:
df=pd.get_dummies(df,columns=["City"],drop_first=True)

In [13]:
df.head().T

                                0         1         2         3         4
Unnamed: 0                      5         6         7         8         9
Month                           8         8         8         8         8
Is_Weekend                      0         0         0         0         0
Humidity_Percent               95        89        82        78        73
Dew_Point_C                  25.7      26.0      25.9      26.1      25.8
Wind_Speed_10m_kmh            4.3       3.4       4.0       6.1       3.5
Precipitation_mm              0.0       0.0       0.0       0.1       0.1
Pressure_MSL_hPa           1003.5    1003.7    1004.1    1004.4    1003.7
Surface_Pressure_hPa       1002.1    1002.3    1002.7    1003.0    1002.3
Solar_Radiation_Wm2          12.0     122.0     327.0     539.0     566.0
Cloud_Cover_Percent           100       100        98        99       100
Sunshine_Seconds              0.0    3600.0    3600.0    3600.0    3600.0
PM2_5_ugm3                   19.1      16.2      12.0      10.1      10.9
PM10_ugm3                    27.6      23.6      17.7      14.9      16.1
PM_Ratio                 0.692029  0.686441  0.677966  0.677852  0.677019
CO_ugm3                     210.0     197.0     180.0     160.0     153.0
NO2_ugm3                     16.4      15.6      14.5      12.8      10.9
SO2_ugm3                      3.5       3.6       3.7       3.6       3.2
O3_ugm3                      26.0      31.0      39.0      50.0      60.0
Dust_ugm3                     0.0       0.0       0.0       0.0       0.0
AOD                          0.13      0.13      0.12      0.13      0.16
US_AQI                       54.0      55.0      55.0      55.0      54.0
Festival_Period                 0         0         0         0         0
Crop_Burning_Season             0         0         0         0         0
City_Ahmedabad              False     False     False     False     False
City_Aizawl                 False     False     False     False     False
City_Bengaluru              False     False     False     False     False
City_Bhopal                 False     False     False     False     False
City_Bhubaneswar            False     False     False     False     False
City_Chandigarh             False     False     False     False     False
City_Chennai                False     False     False     False     False
City_Dehradun               False     False     False     False     False
City_Delhi                  False     False     False     False     False
City_Gangtok                False     False     False     False     False
City_Gurugram               False     False     False     False     False
City_Guwahati               False     False     False     False     False
City_Hyderabad              False     False     False     False     False
City_Imphal                 False     False     False     False     False
City_Itanagar               False     False     False     False     False
City_Jaipur                 False     False     False     False     False
City_Kohima                 False     False     False     False     False
City_Kolkata                False     False     False     False     False
City_Lucknow                False     False     False     False     False
City_Mumbai                 False     False     False     False     False
City_Panaji                 False     False     False     False     False
City_Patna                  False     False     False     False     False
City_Raipur                 False     False     False     False     False
City_Ranchi                 False     False     False     False     False
City_Shillong               False     False     False     False     False
City_Shimla                 False     False     False     False     False
City_Thiruvananthapuram     False     False     False     False     False
City_Visakhapatnam          False     False     False     False     False

In [14]:
import sklearn

In [16]:
X=df.drop(columns=["US_AQI"])
y=df['US_AQI']

In [42]:
X.head(10)

,Unnamed: 0,Month,Is_Weekend,Humidity_Percent,Dew_Point_C,Wind_Speed_10m_kmh,Precipitation_mm,Pressure_MSL_hPa,Surface_Pressure_hPa,Solar_Radiation_Wm2,...,City_Lucknow,City_Mumbai,City_Panaji,City_Patna,City_Raipur,City_Ranchi,City_Shillong,City_Shimla,City_Thiruvananthapuram,City_Visakhapatnam
0,5,8,0,95,25.7,4.3,0.0,1003.5,1002.1,12.0,...,False,False,False,False,False,False,False,False,False,False
1,6,8,0,89,26.0,3.4,0.0,1003.7,1002.3,122.0,...,False,False,False,False,False,False,False,False,False,False
2,7,8,0,82,25.9,4.0,0.0,1004.1,1002.7,327.0,...,False,False,False,False,False,False,False,False,False,False
3,8,8,0,78,26.1,6.1,0.1,1004.4,1003.0,539.0,...,False,False,False,False,False,False,False,False,False,False
4,9,8,0,73,25.8,3.5,0.1,1003.7,1002.3,566.0,...,False,False,False,False,False,False,False,False,False,False
5,10,8,0,70,25.8,4.0,0.2,1002.6,1001.3,636.0,...,False,False,False,False,False,False,False,False,False,False
6,11,8,0,69,26.0,4.3,0.0,1001.8,1000.5,678.0,...,False,False,False,False,False,False,False,False,False,False
7,12,8,0,69,26.3,4.3,0.1,1000.3,999.0,718.0,...,False,False,False,False,False,False,False,False,False,False
8,13,8,0,67,26.4,2.0,0.0,999.1,997.8,738.0,...,False,False,False,False,False,False,False,False,False,False
9,14,8,0,66,26.3,4.2,0.0,998.2,996.9,654.0,...,False,False,False,False,False,False,False,False,False,False

In [19]:
from sklearn.model_selection import train_test_split

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [22]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(n_estimators=100,random_state=42,n_jobs=-1)

n_jobs=-1

Means:Use all CPU cores.Your laptop has multiple cores, so this speeds up training.

In [23]:
model.fit(X_train,y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [27]:
y_pred=model.predict(X_test)

In [24]:
from sklearn.metrics import precision_score,accuracy_score,recall_score,f1_score

In [30]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE  : {mae:.2f}")
print(f"R²   : {r2:.4f}")

MAE  : 9.13
R²   : 0.9220

In [31]:
import pandas as pd

bins = [0, 50, 100, 150, 200, 300, float("inf")]

labels = [
    "Good",
    "Moderate",
    "Unhealthy for Sensitive Groups",
    "Unhealthy",
    "Very Unhealthy",
    "Hazardous"
]

y_test_cat = pd.cut(y_test, bins=bins, labels=labels)
y_pred_cat = pd.cut(y_pred, bins=bins, labels=labels)

In [32]:
accuracy = accuracy_score(y_test_cat, y_pred_cat)

print("Accuracy:", accuracy)

Accuracy: 0.8259532193607002

In [41]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=8,
    random_state=42
)

model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [1]:
y_pred=model.predict(X_test)

NameError: name 'model' is not defined